#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : R-BBmisc
Version  : 1.13
Release  : 47
URL      : https://cran.r-project.org/src/contrib/BBmisc_1.13.tar.gz
Source0  : https://cran.r-project.org/src/contrib/BBmisc_1.13.tar.gz
Summary  : Miscellaneous Helper Functions for B. Bischl
Group    : Development/Tools
License  : BSD-2-Clause
Requires: R-BBmisc-lib = %{version}-%{release}
Requires: R-checkmate
Requires: R-data.table
BuildRequires : R-checkmate
BuildRequires : R-data.table
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
some other guys, mainly for package development.

%package lib
Summary: lib components for the R-BBmisc package.
Group: Libraries

%description lib
lib components for the R-BBmisc package.


%prep
%setup -q -n BBmisc
pushd ..
cp -a BBmisc buildavx2
popd
pushd ..
cp -a BBmisc buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1737135233

%install
export SOURCE_DATE_EPOCH=1737135233
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/BBmisc/DESCRIPTION
/usr/lib64/R/library/BBmisc/INDEX
/usr/lib64/R/library/BBmisc/LICENSE
/usr/lib64/R/library/BBmisc/Meta/Rd.rds
/usr/lib64/R/library/BBmisc/Meta/features.rds
/usr/lib64/R/library/BBmisc/Meta/hsearch.rds
/usr/lib64/R/library/BBmisc/Meta/links.rds
/usr/lib64/R/library/BBmisc/Meta/nsInfo.rds
/usr/lib64/R/library/BBmisc/Meta/package.rds
/usr/lib64/R/library/BBmisc/NAMESPACE
/usr/lib64/R/library/BBmisc/NEWS
/usr/lib64/R/library/BBmisc/R/BBmisc
/usr/lib64/R/library/BBmisc/R/BBmisc.rdb
/usr/lib64/R/library/BBmisc/R/BBmisc.rdx
/usr/lib64/R/library/BBmisc/help/AnIndex
/usr/lib64/R/library/BBmisc/help/BBmisc.rdb
/usr/lib64/R/library/BBmisc/help/BBmisc.rdx
/usr/lib64/R/library/BBmisc/help/aliases.rds
/usr/lib64/R/library/BBmisc/help/paths.rds
/usr/lib64/R/library/BBmisc/html/00Index.html
/usr/lib64/R/library/BBmisc/html/R.css
/usr/lib64/R/library/BBmisc/tests/run-all.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_addClasses.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_asMatrix.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_asQuoted.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_binPack.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_btwn.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_capitalizeStrings.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_checkArg.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_checkListElementClass.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_chunk.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_clipString.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_coalesce.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_collapse.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_collapsef.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_computeMode.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_convertDataFrameCols.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_convertInteger.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_convertListOfRowsToDataFrame.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_convertMatrixType.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_convertRowsToList.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_convertToShortString.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_dapply.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_directory.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_do.call2.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_dropNamed.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_ensureVector.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_explode.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_extractSubList.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_factor.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_filterNull.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getAttributeNames.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getClass1.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getFirstLast.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getMaxColRowIndex.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getMaxIndex.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getOperatingSystem.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getRelativePath.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getUnixTime.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_getUsedFactorLevels.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_hasAttributes.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_insert.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_is.subsetsuperset.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_isFALSE.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_isProperlyNamed.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_isScalarNA.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_isScalarValue.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_isValidNames.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_is_error.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_itostr.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_load2_save2.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_lsort.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_makeDataFrame.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_makeProgressBar.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_makeSimpleFileLogger.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_mapValues.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_namedList.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_nin.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_normalize.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_optimizeSubInts.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_printHead.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_printStrToChar.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_printToChar.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_printf.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_rangeVal.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_requirePackages.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_rowLapply.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_seq.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_setAttribute.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_setClasses.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_setRowColNames.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_setValue.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_sortByCol.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_splitPath.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_splitTime.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_strrepeat.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_suppressAll.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_symdiff.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_system3.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_toRangeStr.R
/usr/lib64/R/library/BBmisc/tests/testthat/test_which.first.last.R

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/BBmisc/libs/BBmisc.so
/V4/usr/lib64/R/library/BBmisc/libs/BBmisc.so
/usr/lib64/R/library/BBmisc/libs/BBmisc.so
