#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-BBmisc
Version  : 1.11
Release  : 3
URL      : https://cran.r-project.org/src/contrib/BBmisc_1.11.tar.gz
Source0  : https://cran.r-project.org/src/contrib/BBmisc_1.11.tar.gz
Summary  : Miscellaneous Helper Functions for B. Bischl
Group    : Development/Tools
License  : BSD-2-Clause
Requires: R-BBmisc-lib
Requires: R-checkmate
BuildRequires : R-checkmate
BuildRequires : clr-R-helpers

%description
some other guys, mainly for package development.

%package lib
Summary: lib components for the R-BBmisc package.
Group: Libraries

%description lib
lib components for the R-BBmisc package.


%prep
%setup -q -c -n BBmisc

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530335786

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1530335786
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library BBmisc
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library BBmisc
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library BBmisc
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library BBmisc|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/BBmisc/DESCRIPTION
/usr/lib64/R/library/BBmisc/INDEX
/usr/lib64/R/library/BBmisc/LICENSE
/usr/lib64/R/library/BBmisc/Meta/Rd.rds
/usr/lib64/R/library/BBmisc/Meta/features.rds
/usr/lib64/R/library/BBmisc/Meta/hsearch.rds
/usr/lib64/R/library/BBmisc/Meta/links.rds
/usr/lib64/R/library/BBmisc/Meta/nsInfo.rds
/usr/lib64/R/library/BBmisc/Meta/package.rds
/usr/lib64/R/library/BBmisc/NAMESPACE
/usr/lib64/R/library/BBmisc/NEWS
/usr/lib64/R/library/BBmisc/R/BBmisc
/usr/lib64/R/library/BBmisc/R/BBmisc.rdb
/usr/lib64/R/library/BBmisc/R/BBmisc.rdx
/usr/lib64/R/library/BBmisc/help/AnIndex
/usr/lib64/R/library/BBmisc/help/BBmisc.rdb
/usr/lib64/R/library/BBmisc/help/BBmisc.rdx
/usr/lib64/R/library/BBmisc/help/aliases.rds
/usr/lib64/R/library/BBmisc/help/paths.rds
/usr/lib64/R/library/BBmisc/html/00Index.html
/usr/lib64/R/library/BBmisc/html/R.css
/usr/lib64/R/library/BBmisc/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/BBmisc/libs/BBmisc.so
/usr/lib64/R/library/BBmisc/libs/BBmisc.so.avx2
/usr/lib64/R/library/BBmisc/libs/BBmisc.so.avx512
